export const labels={unassigned:'장치 미배정',waiting:'연결 대기',connected:'연결',lost:'통신 두절',open:'확인 전',acknowledged:'지휘관 확인',resolved:'조치 종료',sos:'SOS',impact:'충격 관측',prolonged_still:'장시간 무움직임',heat_exposure:'환경 열 노출 주의',link_lost:'통신 두절',link_restored:'통신 복구',moving:'움직임',still:'무움직임',unknown:'움직임 측정 불가'};
export const escape=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sourceLabel=s=>s==='device'?'실제 입력':s==='simulation'?'가상 시험':'미수신';
const profile='<svg viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="10" r="5"/><path d="M6 27c0-7 4-10 10-10s10 3 10 10"/></svg>';
export function rosterView(state,selected){return state.soldiers.map(s=>{
 const sos=state.events.filter(e=>e.node_id===s.assigned_node_id&&e.event_type==='sos'&&e.event_state!=='resolved');
 const p=s.payload;const assigned=!!s.assigned_node_id;
 return `<button class="soldier-row ${sos.length?'has-sos':''} ${s.connection_state==='lost'?'is-lost':''}" data-soldier="${escape(s.soldier_id)}" aria-pressed="${s.soldier_id===selected}"><span class="profile">${profile}<span>${escape(s.soldier_id.slice(-2))}</span></span><span class="soldier-info"><span class="row-top"><strong>병사 ${escape(s.soldier_id.slice(-2))}</strong><span class="state ${escape(s.connection_state)}">${labels[s.connection_state]}</span></span><span class="row-bottom">${assigned?`${p?.heart_rate_bpm==null?'심박 —':escape(p.heart_rate_bpm)+' bpm'} · ${labels[p?.motion_state]||'측정 대기'}${s.data_stale&&p?' · 오래됨':''}`:'장치 배정 없음'}${sos.length?`<span class="sos-label">SOS · ${sos.some(e=>e.event_state==='open')?'확인 전':'조치 전'}</span>`:''}</span></span></button>`;
}).join('');}
export function detailView(state,id,time){
 const s=state.soldiers.find(s=>s.soldier_id===id);if(!s)return '';
 const p=s.payload;
 const items=[['심박',p?.heart_rate_bpm==null?'측정 불가':escape(p.heart_rate_bpm)+' bpm'],['움직임',labels[p?.motion_state]||'측정 없음'],['모드',p?p.mode==='normal'?'일반':'기도비닉':'미수신'],['수신 경과',s.age_ms==null?'없음':Math.floor(s.age_ms/1000)+'초'],['측정 수신',time(s.status_received_at)],['최근 패킷',time(s.last_seen_at)]];
 return `<div class="section-heading"><h3>병사 ${escape(s.soldier_id.slice(-2))} 상세</h3><span>${sourceLabel(s.source)}</span></div>${!s.assigned_node_id?'<p class="empty-small">장치 미배정 · 측정 데이터 없음</p>':`<p class="detail-node">${escape(s.assigned_node_id)} <span>${s.data_stale?'현재 측정값 없음 또는 오래됨':'최근 측정값'}</span></p><dl class="detail-grid">${items.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>${s.connection_state==='connected'?`<p class="detail-note">다음 수신이 없으면 약 ${Math.max(0,Math.ceil((s.timeout_ms-s.age_ms)/1000))}초 후 두절 판정</p>`:''}`}<p class="detail-note">체온 실측 미구현</p>`;
}
export function eventsView(events,state,time,tab){
 if(!events.length)return `<div class="empty-state"><span class="empty-symbol" aria-hidden="true">—</span><strong>${tab==='pending'?'처리할 사건이 없습니다':'처리 완료된 사건이 없습니다'}</strong><p>${tab==='pending'?'새 사건은 이곳에 표시됩니다.':'조치 종료한 사건 기록을 이곳에서 확인합니다.'}</p></div>`;
 return events.map(e=>{
 const soldier=state.soldiers.find(s=>s.assigned_node_id===e.node_id);
 const recovered=e.event_type==='link_lost'&&soldier?.connection_state==='connected';
 return `<article class="incident ${e.event_state==='resolved'?'resolved':''} ${e.event_type==='sos'?'sos-incident':''}"><div class="incident-top"><div><span class="event-kind">${labels[e.event_type]||escape(e.event_type)}</span><h3>${soldier?'병사 '+escape(soldier.soldier_id.slice(-2)):escape(e.node_id)}</h3></div><span class="event-state">${labels[e.event_state]}</span></div>${recovered?'<p class="recovery-note">현재 연결 복구됨 · 사건 조치는 별도</p>':''}<p class="event-meta">${sourceLabel(e.source)} · 최초 ${time(e.first_received_at)}${e.event_type==='sos'?` · 요청 ${e.repeat_count||1}회 · 최근 ${time(e.last_received_at)}`:''}</p><p class="event-meta">확인 ${time(e.acknowledged_at)} · 종료 ${time(e.resolved_at)}</p><div class="event-actions">${e.event_state==='open'?`<button data-event="${escape(e.event_id)}" data-action="ack">확인</button>`:''}${e.event_state!=='resolved'?`<button data-event="${escape(e.event_id)}" data-action="resolve" class="resolve-button">${e.event_type==='sos'?'이 병사 SOS 모두 조치 종료':'현장 조치 후 종료'}</button>`:''}</div></article>`;
 }).join('');
}
export function telemetryView(telemetry,time){return telemetry.length?telemetry.map(e=>`<article class="telemetry-item"><div class="telemetry-heading"><strong>${e.packet_type==='gps'?'GPS 위치':'환경 노드'} <span>${escape(e.node_id)}</span></strong><span>${sourceLabel(e.source)} · ${e.data_stale?'오래됨':'최근 수신'}</span></div><p>${e.packet_type==='environment'?`공기 온도 <b>${escape(e.payload.air_temperature_c??'—')}</b> °C · 습도 <b>${escape(e.payload.humidity_pct??'—')}</b> % · 조도 ADC <b>${escape(e.payload.light_raw??'—')}</b>`:e.payload.fix_valid?`위도 ${escape(e.payload.latitude_deg)} · 경도 ${escape(e.payload.longitude_deg)}`:`현재 위치 미수신${e.last_valid_location?`<br><span class="past-location">과거 좌표 ${escape(e.last_valid_location.latitude_deg)}, ${escape(e.last_valid_location.longitude_deg)} · ${time(e.last_valid_location.received_at)}</span>`:''}`}</p><small>수신 ${time(e.received_at)}</small></article>`).join(''):'<p class="empty-small">환경·GPS 패킷 수신 대기</p>';}
